version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/StatusChecker"
    schedule:
      interval: "monthly"
      
    reviewers:
      - "philipp-c-moser"
      
    target-branch: "main"
